### ISSUE TITLE
unable to study - new version {10.11.5} always crash 

### ISSUE THREAD

**Issue by hajoucha** [helloworld1/AnyMemo#501] opened 2020-08-08 07:25 UTC
After installation of new version 10.11.5. anymemo crashes on xiaomi redmi note 8 pro. android version 10 QP1A (190711.020).
I can launch the app, but any atempt to study results in crash. Seems like new version cannot open the database or so...?

**Comment by helloworld1** [comment] 2020-08-08 13:50
Thanks for reporting issues. I am not able to reproduce the issue on my set of db files. Would you share you db file to me so I can test? You can email me if you don't want file to be public.

**Comment by hajoucha** [comment] 2020-08-08 14:15
ok, I have sent an email with .db file. Hope it helps.  I have also made a screen video from my phone. Beside those, I do not know how to collect more info. But if I get some instruction, I will try to help as much as I can...

**Comment by hajoucha** [comment] 2020-08-08 14:24
![bug](https://user-images.githubusercontent.com/36222165/89712811-96b3b100-d993-11ea-8b4c-d11ebbdcc796.gif)

**Comment by helloworld1** [comment] 2020-08-08 15:39
Thanks for providing the information. I haven't received your email. Did you send to liberty [at] anymemo.org?

**Comment by hajoucha** [comment] 2020-08-08 15:46
aha, sorry, perhaps I have sent to notifications@gihub. Now I have sent another email to liberty.....

**Comment by helloworld1** [comment] 2020-08-08 16:11
I got the db file now and I can reproduce the crash with your db file. It should be related to one of the change we made. I am weighing the option either reverting that change or actually fix the problem.

**Comment by helloworld1** [comment] 2020-08-08 16:15
I will revert the change and release a new version. Thanks a lot for reporting early for this critical issue.
The detail of the issue is that we introduced category auto refresh in this release but somehow your db has "null" category, which caused crash.

**Comment by helloworld1** [comment] 2020-08-08 16:25
The issue is now fixed in version 10.11.6 with this commit: https://github.com/helloworld1/AnyMemo/commit/a0f4fb3b7532152e8d5a3f7cac68f9cb69e2f168

**Closed by helloworld1** 2020-08-08 16:25 UTC

**Comment by hajoucha** [comment] 2020-08-08 16:38
hm, maybe the unusual behavior of my .db file is because I imported .cvs and converted that into .db file? Also, I have uploaded the file to my pc (linux) and changed it using sql and than uploaded back to my phone?

**Comment by helloworld1** [comment] 2020-08-08 16:43
Yea, I think some import path can result in null category instead of empty category. To maintain compatibility, AnyMemo should treat it as empty category. It's an oversight on our end. Sorry for the inconveniences. And thanks again for working with us to resolve quickly.
